packages:
  - "apps/*"
  - "core"
  - "packages/*"

allowBuilds:
  esbuild: false

catalog:
  "@biomejs/biome": 2.5.6
  "@types/node": ^24.13.3
  "@vitejs/plugin-vue": ^6.0.8
  typescript: ^7.0.2
  vite: ^8.0.16
  vite-plugin-singlefile: ^2.3.0
  vitest: ^4.1.7
  vue: ^3.5.41
  vue-tsc: ^3.2.9
